CREATE TABLE #STU(SID INT,SNAME VARCHAR(3))///SYNTAX FOR CREATING TEMPORARY TABLES

-----------------------------------------------------------
CREATE DATABASE MYDB //SYNTAX FOR CREATING DATABASES

---------------------------------------------------
USE MYDB   // SYNTAX FOR USING DATABASE FROM DATABASES

------------------------------------------------------
///////////////// SUB LANGUAGES IN SEQUEL /////

------------------DDL -DATA-DEFINITION LANGUAGE-----------

-------------------------------------------------------------------
--COMMANDS==== --CREATE--ALTER--SP_RENAME--TRUNCATE--DROP---------

EXAMPLE---CREATE DATABASE DB-----------------

CREATE TABLE MYTABLE(ID INT,NAME VARCHAR(5));------------------

----------------------------------------
EXAMPLE---SP_HELP TABLENAME ----SYNTAX -- FOR VIEWING TABLE STRUCTURE
-----------------------------------------------------------

USING-- ALTER-ALTER  COMMAND-------------------------------
----CHANGING SIZE AND DATATYPE OF OLD COLUMN TO NEW---
EXAMPLE-- ALTER TABLE [TNAME] ALTER COLUMN [COLNAME] NEWTYPE [NEWSIZE]

-----USING--- ALTER- ADD 
------ADDING NEW COLUMNS AT END OF TABLE COLUMNS-----
EXAMPLE-- ALTER TABLE [TNAME] ADD [NEWCOL1] [SIZE],[NEWCOL2] [SIZE]------------

USING SP_RENAME --------------
----FOR CHANGING OLD TABLE NAMES OR COLUMN NAMES TO NEW NAMES--
EXAMPL1-- SP_RENAME '[TABLENAME].[OLDCOLNAME]', '[NEWCOLNAME]
--EXAMPL2--SP_RENAME '[OLDTABNAME]','[NEWTABNAME]'

USING--ALTER-DROP--------------
----FOR DROPPING UNWANTED COLUMNS FROM TABLES---
EXAMPLE-- ALTER TABLE [TABLENAME] DROP COLUMN [COL1],[COL2]...---

USING--TRUNCATE--------------
---FOR DELETING DATA BUT NOT STRUCTURE OF A TABLE-----
EXAMPLE-- TRUNCATE TABLE [TABLENAME]

USING----DROP--------
--FOR DELETING DATA AND STRUCTURE PERMANENTLY...FROM DATABASE
EXAMPLE-- DROP TABLE [TABLENAME]
///////////////////////////////////////////////////////////////////////////////////

                   -------CREATING-ALTERING--DROPING--DATABASES----
------------------------------------------------------------------------------------------

USING-----CREATING DATABASE -- WITH---EXPLICITLY-----[NAME,FILENAME,SIZE,MAXSIZE,FILEGROWTH]----
--SYNTAX====CREATE DATABASE [DBNAME] ON(DATAFILE PROPERTIES ABOVE) LOGON(LOGFILE PROPERTIES ABOVE)
EXAMPLE--CREATE DATABASE MYDB ON(NAME="XYZMDF",FILENAME="E://MYDB.MDF",SIZE=8MB,MAXSIZE=20MB,FILEGROWTH=1MB) 
         LOGON(NAME="XYZLDF",FILENAME="E://MYDBLOG.LDF",SIZE=4MB,MAXSIZE=12MB,FILEGROWTH=1MB))

USING ----ALTERING DATABASE --FILES--MDF --OR--LDF--EXPLICITLY---
--SYNTAX--  ALTER DATABASE [DBNAME] ADD FILE(MDF FILE PROPERTIES)
            ALTER DATABASE [DBNAME] ADD LOGFILE(LOGFILE PROPERTIES )

USING ---ALTER--MODIFY-FILE----
--SYNTAX---CHANGING SIZE OF .LDF OR .MDF FILES----
EXAMPLE--ALTER DATABASE [DBNAME] MODIFY FILE (SET NEW PROPERTIES MDF OR LDF SAME FOR BOTH)

USING--ALTER-REMOVE-FILE-
-ONLY--SECONDARY--FILES--ARE--REMOVED--BUT-NOT--PRIMARY--FILES--
--SYNTAX--REMOVING--MDF-OR--LDF--FILES--FROM--EXISTING-DATABASES----
EXAMPLE-- ALTER DATABASE [DBNAME] REMOVE FILE [NAME]i.e'MNO' OR 'PQR'

USING---ALTER-MODIFY--
--FOR--RENAMEING --DATABASE NAMES---
EXAMPLE---ALTER DATABASE [OLDDBNAME] MODIFY NAME = [NEWDBNAME]

USING--DROP--DATABASE-- 
SYNTAX--FOR--DROPPING--DATABASE--
EXAMPLE--DROP DATABASE MYDB
